### ISSUE TITLE
coredns policy middleware doesn't clean up on shutdown

### ISSUE THREAD

**Issue by johnbelamaric** [infobloxopen/themis#7]
From @yuewko, if you do a restart via SIGUSR1 to point to a different PDP because the current one is down, the go routine that manages the original connection continues to spew errors.

This is because the Shutdown callback is not implemented.

**Comment by vasili-v** [comment]
@UladzimirTrehubenka, as I recall shutdown has been already added. Is it correct? If so we can just close the item.

**Comment by UladzimirTrehubenka** [comment]
Yes, this has been fixed already hence close the Issue.
